server:
  port: 8081

spring:
  application:
    name: 'fornecedor'
  # zipkin
  zipkin:
    sender: web
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

