server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /home/welisson/Projetos-estudos/projetos/Microservices/microsservicos-workspace-aula-1/microservicos/microservices-config-repo
